### ISSUE TITLE
enermaps-api is downloading the 50 datasets everytime

### ISSUE THREAD

**Issue by zarch** [enermaps/enermaps#365]
Every time I do a small change on one of the file in the cm that I'm developing when I execute the `sudo docker-compose up --build` the enermaps-api docker it took more or less 10 minutes to dowload again the datsets.

I tried to modify the `docker-compose.yml` file to have a permanent local volume to avoid to download the dataset every time, so I change the volume definition to:

```yml
volumes:
  geodb: 
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/pietro/src/eurac/enermaps/enermaps_volumes/geodb
  cm_outputs: 
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/pietro/src/eurac/enermaps/enermaps_volumes/cm_outputs
  caddy-data: 
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/pietro/src/eurac/enermaps/enermaps_volumes/caddy-data
  caddy-config: 
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/pietro/src/eurac/enermaps/enermaps_volumes/caddy-config
  redis-data: 
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/pietro/src/eurac/enermaps/enermaps_volumes/redis-data
  flower-data: 
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/pietro/src/eurac/enermaps/enermaps_volumes/flower-data
```

However I still have:

```bash
» sudo docker-compose up --build
...
enermaps-api-1             | 2021-10-13 10:40:47,404 INFO app MainThread : ... fetch done in 24 seconds
enermaps-api-1             | 2021-10-13 10:41:19,144 INFO app MainThread : ... save done in 31 seconds.
enermaps-api-1             | 2021-10-13 10:41:19,144 INFO app MainThread : Get/update nuts/lau <NUTS1>...
enermaps-api-1             | 2021-10-13 10:41:30,278 INFO app MainThread : ... fetch done in 11 seconds
enermaps-api-1             | 2021-10-13 10:41:32,464 INFO app MainThread : ... save done in 2 seconds.
enermaps-api-1             | 2021-10-13 10:41:32,464 INFO app MainThread : Get/update nuts/lau <NUTS2>...
enermaps-api-1             | 2021-10-13 10:41:35,574 INFO app MainThread : ... fetch done in 3 seconds
enermaps-api-1             | 2021-10-13 10:41:37,178 INFO app MainThread : ... save done in 1 seconds.
enermaps-api-1             | 2021-10-13 10:41:37,178 INFO app MainThread : Get/update nuts/lau <NUTS3>...
enermaps-api-1             | 2021-10-13 10:41:45,478 INFO app MainThread : ... fetch done in 8 seconds
enermaps-api-1             | 2021-10-13 10:41:47,582 INFO app MainThread : ... save done in 2 seconds.
...
enermaps-api-1             | 2021-10-13 10:52:19,416 INFO app MainThread : Download dataset <49>...
enermaps-api-1             | 2021-10-13 10:52:23,903 INFO app MainThread : ... fetch done in 4 seconds
enermaps-api-1             | Warning 6: Field start_at create as date field, though DateTime requested.
enermaps-api-1             | 2021-10-13 10:52:26,110 INFO app MainThread : ... save done in 2 seconds.
enermaps-api-1             | 2021-10-13 10:52:26,110 INFO app MainThread : Download dataset <50>...
enermaps-api-1             | 2021-10-13 10:52:33,026 INFO app MainThread : ... fetch done in 6 seconds
enermaps-api-1             | Warning 6: Field start_at create as date field, though DateTime requested.
enermaps-api-1             | 2021-10-13 10:52:34,552 INFO app MainThread : ... save done in 1 seconds.
enermaps-api-1             | 2021-10-13 10:52:34,555 INFO root MainThread : startup hook finished

```

Do you have any hints to avoid to download the dataset at every run?
Do you know why the created volumes remain empty?
